apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: alertmanager
    name: alertmanager
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: alertmanager
      spec:
        containers:
        - args:
          - -config.file=/etc/alertmananger/alertmanager.yml
          - -web.external-url=http://alertmanager.monitoring.svc.cluster.local
          image: prom/alertmanager:v0.9.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 9093
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          name: alertmanager
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 9093
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 200M
          volumeMounts:
          - mountPath: /etc/alertmananger
            name: alertmanager-config
        volumes:
        - configMap:
            items:
            - key: alertmanager.yml
              path: alertmanager.yml
            name: alertmanager
          name: alertmanager-config

- apiVersion: v1
  kind: Service
  metadata:
    name: alertmanager
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 9093
    selector:
      app: alertmanager

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: alertmanager
  data:
    alertmanager.yml: |
      route:
        receiver: 'slack'
        group_by: ['instance']

      receivers:
        - name: 'slack'
          slack_configs:
            - send_resolved: true
              text: '{{.CommonAnnotations.summary}}'
              username: 'Prometheus'
              channel: '#operations'
              api_url: ''
