apiVersion: v1
kind: List
items:

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
    labels:
      app: blackbox-exporter
    name: blackbox-exporter
  spec:
    replicas: 8
    template:
      metadata:
        labels:
          app: blackbox-exporter
      spec:
        containers:
        - args:
          - --config.file=/etc/blackbox_exporter/blackbox.yml
          image: prom/blackbox-exporter:v0.10.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 9115
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          name: blackbox-exporter
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 9115
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 200M
          volumeMounts:
          - mountPath: /etc/blackbox_exporter
            name: blackbox-exporter-config
        volumes:
        - configMap:
            defaultMode: 420
            items:
            - key: blackbox.yml
              path: blackbox.yml
            name: blackbox-exporter
          name: blackbox-exporter-config

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    name: blackbox-exporter
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 9115
    selector:
      app: blackbox-exporter

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: blackbox-exporter
  data:
    blackbox.yml: |
      modules:
        tcp_connect:
          prober: tcp
          timeout: 5s
        icmp:
          prober: icmp
          timeout: 5s
