kind: PersistentVolume
apiVersion: v1
metadata:
  name: extra-pv-volume
  namespace: monitoring
  labels:
    type: iscsi
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.255.10:3260
    portals: ['192.168.255.11:3260', '192.168.255.12:3260', '192.168.255.13:3260', '192.168.255.14:3260']
    iqn: iqn.2001-05.com.equallogic:0-8a0906-625b41907-5290000001559bdb-k8s.extra
    lun: 0
    fsType: ext4
    readOnly: false