apiVersion: v1
kind: List
items:

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: logstash
    name: logstash
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: logstash
      spec:
        containers:
        - image: docker.elastic.co/logstash/logstash:5.6.2
          name: logstash
          resources:
            limits:
              memory: 512M
          volumeMounts:
          - mountPath: /usr/share/logstash/pipeline
            name: logstash-pipeline-config
          - mountPath: /usr/share/logstash/config
            name: logstash-config
        volumes:
        - configMap:
            items:
            - key: pipeline.logstash.yml
              path: logstash.yml
            name: logstash
          name: logstash-pipeline-config
        - configMap:
            items:
            - key: config.logstash.yml
              path: logstash.yml
            name: logstash
          name: logstash-config

- apiVersion: v1
  kind: Service
  metadata:
    name: logstash
  spec:
    clusterIP: "10.97.0.20"
    ports:
    - name: json
      port: 5959
      protocol: TCP
      targetPort: 5959
    - name: snmptraps
      port: 162
      protocol: UDP
      targetPort: 1062
    selector:
      app: logstash

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: logstash
  data:
    config.logstash.yml: |
      http.host: "0.0.0.0"
      path.config: /usr/share/logstash/pipeline
      xpack.monitoring.enabled: false
    pipeline.logstash.yml: |
      input {
          tcp {
              port => 5959
              codec => json
          }
          snmptrap {
              community => public
              type => snmptrap
          }
      }
      filter {
          if [type] == "snmptrap" {
              if "NATIVE_VLAN_MISMATCH" in [message] {
                  drop {}
              }
              mutate {
                  remove_field => [ "message" ]
              }
          }
      }
      output {
          stdout { codec => rubydebug }
      }
