apiVersion: v1
data:
  # Config file for prometheus
  # You can reload it with
  # kubectl replace -f prometheus-config.yaml
  # kubectl exec (kubectl get pods -l app=prometheus -n monitoring -o name | cut -d/ -f2) -n monitoring -- killall -HUP prometheus
  prometheus.yml: |-
    # my global config
    global:
      scrape_interval:     15s # By default, scrape targets every 15 seconds.
      evaluation_interval: 15s # By default, scrape targets every 15 seconds.
      # scrape_timeout is set to the global default (10s).
      # Attach these labels to any time series or alerts when communicating with
      # external systems (federation, remote storage, Alertmanager).
      external_labels:
          monitor: 'NPF'

    # Load and evaluate rules in this file every 'evaluation_interval' seconds.
    rule_files:
      # - "alert.rules"
      # - "first.rules"
      # - "second.rules"

    scrape_configs:
      # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
      - job_name: 'prometheus'

        # Override the global default and scrape targets from this job every 5 seconds.
        scrape_interval: 5s

        metrics_path: '/prometheus/metrics'
        static_configs:
          - targets:
            - 'localhost:9090'
      
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus
  namespace: monitoring