apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: monitoring
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: pushgateway
    namespace: monitoring
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: pushgateway
      spec:
        containers:
        - name: pushgateway
          image: prom/pushgateway:v0.4.0
          resources:
            limits:
              memory: 200M
          livenessProbe:
            httpGet:
              path: /
              port: 9091
            initialDelaySeconds: 1
            timeoutSeconds: 1
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 9091
            initialDelaySeconds: 1
            timeoutSeconds: 1
            periodSeconds: 3
- kind: Service
  apiVersion: v1
  metadata:
    name: pushgateway
    namespace: monitoring
  spec:
    selector:
      app: pushgateway
    ports:
      - protocol: TCP
        port: 80
        targetPort: 9091
