apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: core
spec:
  clusterIP: 10.97.10.10
  ports:
    - port: 9090
      protocol: TCP
      name: webui
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: core
