kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: prometheus
  annotations:
    argocd.argoproj.io/sync-wave: "2"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
